spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id : ptt
         uri: lb://device-adapttion
         predicates:
          - Path=/ptt-server/**
         filters:
          - IpLimitFilter
          - PermissionLimitFilter

server:
  port: 4444
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/