#redis
#redis
spring:
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    timeout: 6000
  application:
    name: auth
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 5555
  servlet:
    context-path: /oauth2/


