server:
  port: 4444

spring:
  application:
    name: gateway
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: device
          uri: lb://device
          predicates:
          - Path=/device/**
          filters:
          - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
          - Path=/auth/**
          filters:
          - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

