server:
  port: 4444

spring:
  application:
    name: gateway
  cloud:
      gateway:
        locator:
          enabled: true
        routes:
        - id: device
          uri: lb://device
          predicates:
          - Path=/device/**
          filters:
          - IpLimitFilter
          - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
          - Path=/auth/**
          filters:
          - IpLimitFilter
          - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_new_ptt?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:/com/dnp/service/zuul/modular/autoCode/dao/impl/*Mapper.xml
  typeAliasesPackage: com.dnp.service.zuul.modular.autoCode.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multiple  ResultSetsEnabled: true
