spring:
  application:
    name: eureka-center
server:
  port: 1111
eureka:
  client:
    service-url:
       defaultZone: http://localhost:1111/eureka/
    fetch-registry: false
    register-with-eureka: false